Wqp 1381 - NWIS ETL (NATDB portion)
NWQMC/etl-nwis-lookups pull request #3
Opened 2019-03-22 15:29 UTC by mbucknell

I have left in the sql script for NEMI. We will be putting this in it's own repo. Some changes were also made the schema-nwis-ws-star as part of this work.

2019-03-22 15:31 UTC, mbucknell commented on src/main/java/gov/acwi/wqp/etl/methWithCit/TaskMethWithCitMeth.java
> +package gov.acwi.wqp.etl.methWithCit;
I implemented this with a tasklet because the standard reader failed mysteriously when trying to perform the Min aggregation

2019-03-22 15:33 UTC, mbucknell commented on src/main/java/gov/acwi/wqp/etl/parm/AddMultiplierColumn.java
> +package gov.acwi.wqp.etl.parm;
The multiplier column from parm_alias is inserted into the parm table with this tasklet.

2019-03-25 14:05 UTC, dsteinich requested changes
I wish GitHub didn't limit display to 80 characters - luckily these classes are small so it is not a big hassle to scroll to see the sql.

2019-03-25 14:05 UTC, dsteinich commented on src/main/java/gov/acwi/wqp/etl/aquiferType/TransformAquiferType.java
> +	DataSource natdbDataSource;
Codacy Flagged this as missing the scope.

2019-03-25 14:05 UTC, dsteinich commented on src/main/java/gov/acwi/wqp/etl/natAqfr/TransformNatAqfr.java
> +				.rowMapper(new NatAqfrRowMapper())
Given that a new row mapper is passed here, there is no need for the bean definition of it below. The are a bunch of these that can be cleaned up.

2019-03-25 14:05 UTC, dsteinich commented on src/main/resources/sql/parm.sql
> +join
This is the join causing Laura's issue... (wrong counts on USGS activity pulls) No suggestions at this time.

2019-03-25 14:12 UTC, mbucknell commented on src/main/java/gov/acwi/wqp/etl/natAqfr/TransformNatAqfr.java
> +				.rowMapper(new NatAqfrRowMapper())
I'm confused. The bean declared below this is NatAqfrProcessor.  I think I need that one?

2019-03-25 17:23 UTC, merged